[package]
name = "rust-text-file-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
regex  = "1.5.4"
zip = "0.5.13"
tokio = { version = "1", features = ["full"] }

